### ISSUE TITLE
Directive should not use `=` operator

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-training-public#107]
Some examples in the training docs use `=` in directive. For example 

```
process BASICEXAMPLE {
  debug=true

  input:
  val x

  script:
  """
  echo process job $x
  """
}
```

However, it should be 

```
process BASICEXAMPLE {
  debug true

  input:
  val x

  script:
  """
  echo process job $x
  """
}
```

Equals should be used instead in the nexflow.config file

**Comment by mribeirodantas** [comment]
Thanks, Paolo! I will fix this. Just to make sure I understood it right.

In `nextflow.config`, it is:
```
process.container = nextflow/rnaseq-nf
```

But if I want to set this within a process block, it'll be:
```
container nextflow/rnaseq-nf
```

Same reasoning for all directives, right?

**Comment by pditommaso** [comment]
Yes, with quotes around the values tho (!) 

```
process.container = 'nextflow/rnaseq-nf'
```
