### ISSUE TITLE
GitPod: `workspaceLocation`

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-training-public#116]
Set the workspace location so that we don't have to see the repo files:

https://www.gitpod.io/docs/references/gitpod-yml#workspacelocation

**Comment by chriswyatt1** [comment]
I can't fix this. I have tried setting this in the gitpod.yml. All it does is remove the explorer completely. 

Set using

workspaceLocation: "./nf-training"
workspaceLocation: "/workspace/nf-training"
checkoutLocation: "./nf-training"

**Comment by ewels** [comment]
I was going to suggest making an issue about it, but then saw you already did 😅 

x-ref: https://github.com/gitpod-io/gitpod/issues/13608

**Comment by chriswyatt1** [comment]
Thanks, I should have linked here! Hopefully theres an obvious way to do this that I missed.

**Comment by chriswyatt1** [comment]
Fix in PR #119
