### ISSUE TITLE
Feedback from seqera team

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-training-public#4]
Creating this issue here to keep track of the feedback

**Abhinav:** 

1. Include pair programming to allow people to use their knowledge practically

2. Work on an advanced course 
-  Show basic errors to people, how to debug
- How to develop a workflow and make it cloud ready ( + tower ready )
- Transition a workflow from DSL1 to DSL2

**Comment by ewels** [comment]
Cleaning up old issues...

Not sure how we would work pair programming into the actual course material? I think that's more up to the instructors. Correct me if you have something specific in mind.

Advanced course done by @robsyme, will be merged into this repo soon.
