### ISSUE TITLE
Gitpod loads old deleted untracked files into the IDE

### ISSUE THREAD

**Issue by chriswyatt1** [seqeralabs/nf-training-public#56]
For some reason, we can see all old deleted files int he IDE, they are listed as untracked, but we need to get rid of them

<img width="293" alt="image" src="https://user-images.githubusercontent.com/9978862/159159420-3b5fb098-1367-4bfe-99af-25187add9897.png">

The entries with a green U, are untracked, but they should not be there at all, in this master branch

**Comment by pditommaso** [comment]
Not sure to understand, which files are deleted?

**Comment by chriswyatt1** [comment]
Thanks Paolo,,  so in the master branch, these are the files I have:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/9978862/159169635-11a0cfd4-68ad-4309-8678-cd44345433c5.png">

But when I open Gitpod, it opens up all these other files, that I assume are old deleted files. Then within gitpod, I remove all these extra files, and when I go to commit, it says there are no changes to be commited...

If there some kind of hidden config maybe

**Comment by chriswyatt1** [comment]
I tried to change the gitpod.yml for branches to false,,, in case it was loading files from other branches:
https://github.com/seqeralabs/nf-training-public/blob/master/.gitpod.yml  (line 6).

But this had no effect

**Comment by pditommaso** [comment]
I guess it's something related to the pre-build which is not getting refreshed.

**Comment by chriswyatt1** [comment]
Ah ok, yeah, thats what I thought with the last post. OK, maybe I try playing more with the .gitpod.yml

**Comment by chriswyatt1** [comment]
Forcing a restart of the pre-build fails:
https://gitpod.io/#prebuild/https://github.com/seqeralabs/nf-training-public
So this must be it:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/9978862/159170303-cabcebae-eabf-470f-a080-0ba3d22b9c72.png">

**Comment by chriswyatt1** [comment]
OKAY, finally it works.
The gitpod.yml initialisation was curling in the material from AWS S3. This was the old way we did it (because of privacy), so it was duplicating the files and folders locally! Was confused where it all came from. Thanks for looking

**Comment by pditommaso** [comment]
Ah, makes sense now
