### ISSUE TITLE
Reopening Gitpod after time out- does not have the port exposed

### ISSUE THREAD

**Issue by chriswyatt1** [seqeralabs/nf-training-public#58]
When gitpod times out, and you click the reopen session option, the Tutorial page does not come up :

<img width="507" alt="image" src="https://user-images.githubusercontent.com/9978862/159250876-9987d552-3bf1-40b2-aeae-73676986a491.png">
 
 Need to find fix. Temporarily, we can ask users to reopen a new workspace,,, but then their progress will be lost

**Comment by pditommaso** [comment]
There's no control on the timeout duration?

**Comment by swampie** [comment]
Fixed by adding a gp await-port: looks like URL can't be open until the
vscode port becomes available
