### ISSUE TITLE
RNASeq with AWS Batch is not working with Gitpod environment

### ISSUE THREAD

**Issue by evanfloden** [seqeralabs/nf-training-public#70]
### Description

The basic RNASeq example is no longer working with AWS Batch in the Gitpod environment.

### Error

```
gitpod /workspace/nf-training-public/nf-training (master) $ nextflow run nextflow-io/rnaseq-nf -profile batch
N E X T F L O W  ~  version 21.10.6
Pulling nextflow-io/rnaseq-nf ...
 downloaded from https://github.com/nextflow-io/rnaseq-nf.git
Launching `nextflow-io/rnaseq-nf` [soggy_snyder] - revision: f05cb38541 [master]
Downloading plugin nf-amazon@1.3.4
 R N A S E Q - N F   P I P E L I N E
 ===================================
 transcriptome: s3://rnaseq-nf/data/ggal/transcript.fa
 reads        : s3://rnaseq-nf/data/ggal/lung_{1,2}.fq
 outdir       : results
 
Uploading local `bin` scripts folder to s3://nextflow-ci/work/tmp/f8/069e068becfa5d06597412f65fd1d0/bin
No files match pattern `lung_{1,2}.fq` at path: /rnaseq-nf/data/ggal/
No files match pattern `lung_{1,2}.fq` at path: /rnaseq-nf/data/ggal/
```

### Logs

See [gist here](https://gist.github.com/evanfloden/e0c0af2485462df7108bae722f3cee03).

### How to replicate

1. Opening the GitPod environment: **[gitpod.io/#https://github.com/seqeralabs/nf-training-public](https://gitpod.io/#https://github.com/seqeralabs/nf-training-public)**
2. Export AWS credentials
3. In the terminal run `$ nextflow run nextflow-io/rnaseq-nf -profile batch`

**Comment by chriswyatt1** [comment]
@evanfloden Can you try with this branch : https://gitpod.io/#https://github.com/seqeralabs/nf-training-public/tree/Revert_container

We can make this master if it works
