### ISSUE TITLE
Fix Youtube link

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/nf-training-public#96]
In the Learning landing page, https://seqera.io/nextflow/learn/,

at the end of the section *Nextflow Workshop from Seqera Labs*,

The Youtube link currently points to the July 2020 playlist.
I suspect it should point to the April 2022 one: https://www.youtube.com/playlist?list=PLPZ8WHdZGxmUVZRUfua8CsjuhjZ96t62R

**Comment by chriswyatt1** [comment]
Fixed, thanks, now it points to the correct link
